"""English regression inputs for the classifier breadth probe.

Examples are synthetic or generic rule declarations. Empty route/hazard labels
are unspecified expectations, not negative assertions. Some labels describe the
lexical test double rather than production behavior; the probe lists deliberate
disagreements explicitly. Source-session references and line metadata are not kept.
Changes to these inputs require fresh live measurements before claiming acceptance.
"""


REGRESSION_CASES = [
    {
        "text": 'take the copper hinge',
        "route": 'planner',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'I take the copper hinge',
        "route": 'planner',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'grab the rusty key',
        "route": 'planner',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'I lift the fallen banner',
        "route": 'planner',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'loot the chest',
        "route": 'planner',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'take the sword from the merchant',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": "steal the merchant's purse",
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'pickpocket the stranger',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": "take reed thug's coin purse",
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'npc_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'approach the traders and say hello',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1', 'market', ())",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'steal their rope',
        "route": 'risk',
        "hazard": 'theft',
        "scope": "other:TrustedScope('session-1', 'market', ()) + active_focus from prior turn",
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the purse from the guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal it from the guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take it from the man in the corner',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the coin from the thief',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take his sword',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal her necklace',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the key from the drawer',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the coin from the chest',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'grab the sword from the rack',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the potion from the shelf',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'loot the gold from the crate',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the coin from him',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the ring from her',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the pouch from reed thug',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'npc_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the queen from the board',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the king from the chessboard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the knight from the board',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'steal the queen off the chessboard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the guard rail',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the shin guard from the locker',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the arm guard from the chest',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the elbow guard from the rack',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the wrist guard from the shelf',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the mouth guard from the bag',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the queen statue from the shelf',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the king piece from the box',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "grab the captain's chest",
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": "loot the king's tomb",
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": "take the queen's crown",
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the old guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the crown from the young queen',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take it from the wounded guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the ring from the sleeping merchant',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the wounded guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'grab the old man',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'pickpocket the young stranger',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'I take the potion, thinking about her',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'grab the key, then look for her',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword before her arrival',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'loot the chest while waiting for their signal',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'grab their purse',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the potion from the old wooden guard station',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the old wooden guard station',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword, her idea was clever',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'grab the potion near her, quietly',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword from the tall old bearded guard standing there',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the coin purse from the tall old bearded guard nearby',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the very tall old bearded guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the very tall old grizzled bearded guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'pickpocket the very tall old grizzled bearded stranger',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the very tall old grizzled bearded guard standing there',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword and the guard fled',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword, then the guard attacked',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword but the guard noticed',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword while the guard slept',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword from the chest and the guard shouted',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the sword from the old chest, near the guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the pouch from the tall guard standing watch',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the guard standing watch',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the guard who arrived late',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the guard who arrived late',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the guard sent to watch',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the coin from the merchant who just arrived',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the queen from the tarnished board',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the king from the polished chessboard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the queen from the board, gleaming',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the guard captain of the watch',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the sword from the guard captain of the watch',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the pouch from the guard standing there',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the guard from the tower',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the guard from his post',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'steal the queen from the throne room',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'grab the merchant from the crowd',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the stranger from the cell',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the queen from the rusted cabinet',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the knee guard from the shelf',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the ear guard from the rack',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the hand guard from the box',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the leg guard from the crate',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the neck guard from the peg',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the foot guard from the bin',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the old shin guard from the locker',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the tarnished shin guard from the locker',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the queen from the guard',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take the shin guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the arm guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the elbow guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the wrist guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the mouth guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the knee guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the ear guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the hand guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the leg guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the neck guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the foot guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the old shin guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the tarnished shin guard',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the shin guard, standing there',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Could I defeat him? Is he armed?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'He seems tough. Could I defeat him? Is he armed?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Should I take him?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Would I be able to take him?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Could I take him?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'What if I take him? What does he carry?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'What would happen if I take him?',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I take it from reed thug. What next?',
        "route": 'risk',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab reed thug. What happens now?',
        "route": 'risk',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab reed thug?',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'Should I open the door, then I stab reed thug?',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'Should I open the door? Then I stab reed thug.',
        "route": 'risk',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'What if I open the door, then I take his purse?',
        "route": 'risk',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I am attacking reed thug',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I keep stabbing reed thug',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'reed thug is punching me',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I killed reed thug',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I harmed reed thug',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I use my persuasion skill to calm the guard',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I lead the horse into the stable',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I feel upbeat about our chances',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'there is harmony in the camp',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'this place feels harmless',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am kneeling before the altar',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I hear a heartbeat',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'he is my sidekick',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'we enter the nightclub',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'the clubhouse is empty',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'she plays the harmonica',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I see roadkill on the path',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'that would be overkill',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I kickstart the engine',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'the kickoff is soon',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I take the shortcut through the market',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I backstab reed thug',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm not attacking; I only want to comfort her",
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am not attacking, I just want to talk',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I will not attack',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I don't attack the guard",
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I wouldn't stab him",
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'no, I never hit anyone',
        "route": '',
        "hazard": '',
        "scope": 'npc_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack the guard',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": "I said I wouldn't, then I stab him anyway",
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": "I won't back down, so I attack",
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'not now, but I attack the guard',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'npc_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": '@GM I attack the choir listener immediately, why was I refused?',
        "route": 'out_of_character',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; none.',
    },
    {
        "text": 'ooc I stab the choir listener now -- does that need a roll?',
        "route": 'out_of_character',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; none.',
    },
    {
        "text": 'gm, do I need to confirm when I stab the choir listener now now?',
        "route": 'out_of_character',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; none.',
    },
    {
        "text": 'ooc I punch the barkeep, is that allowed?',
        "route": 'out_of_character',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; none.',
    },
    {
        "text": 'ooc I stab the choir listener now',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'gm I stab the choir listener now',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab the choir listener now. gm?',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab the choir listener now! ooc?',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab the choir listener now now?',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'rules question: if I stab the choir listener now do I roll?',
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": 'ooc I kiss the stranger?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": '@GM I kiss the stranger, is that allowed?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'ooc i buy a rope for 5 coin?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'gm, I buy the ring?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'gm i persuade the guard to let us pass?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'ooc I threaten the barkeep?',
        "route": 'social',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'stab the Choir Listener with my dagger',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener in the throat',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the choir listener with my sword',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'kick the choir listener hard',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'punch the choir listener in the face twice',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'swing my axe at the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener again',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack the choir listener immediately',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'i stab the choir listener now',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm attacking the choir listener",
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am stabbing the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am attacking the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attacking the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener and the fishwife',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'kill the smuggler next to the choir listener',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener and the child',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener with my dagger and then the acolyte',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I stab the choir listener now and the fishwife',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm stabbing the choir listener and the fishwife",
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am attacking the smuggler next to the choir listener',
        "route": '',
        "hazard": '',
        "scope": 'second_target',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I stab Rade with my long knife',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener with my long knife',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I hit the choir listener with my heavy iron mace',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'swing my old rusty axe at the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'cut the choir listener with my sharp short blade',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I yell "help, help! I\'m being attacked by Rade!!!"',
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": 'I shout "he attacked me, someone help!"',
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": "I'm being attacked by Rade",
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": 'I was attacked on the road last night',
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": 'we got attacked at the shrine',
        "route": '',
        "hazard": 'none',
        "scope": 'fight',
        "note": 'Regression case: context-dependent route; none.',
    },
    {
        "text": 'I say "I\'ve got a lot of gutting to do too" and stab the stranger',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I was attacked first, so now I stab the stranger back',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": "Who's turn is it",
        "route": 'out_of_character',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; no positive hazard label.',
    },
    {
        "text": 'whose turn is it?',
        "route": 'out_of_character',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; no positive hazard label.',
    },
    {
        "text": 'What round is it',
        "route": 'out_of_character',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; no positive hazard label.',
    },
    {
        "text": 'how many actions do I have left',
        "route": 'out_of_character',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: out_of_character; no positive hazard label.',
    },
    {
        "text": 'I spend my turn stabbing the choir listener',
        "route": 'risk',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I turn around',
        "route": 'planner',
        "hazard": '',
        "scope": 'fight',
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'I move up to striking distance',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I close the distance and strike the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I step forward and attack',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'advance and cut the choir listener',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I move toward the child and strike',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','market-child'),('rill',), both alive); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I punch the trader in the face and take the rope',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'stab the guard and take the lamp',
        "route": 'risk',
        "hazard": 'violence',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; violence.',
    },
    {
        "text": 'I slash at the merchant, then take his stall',
        "route": 'risk',
        "hazard": 'theft',
        "scope": 'no_one_present',
        "note": 'Regression case: risk; theft.',
    },
    {
        "text": 'take a break',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the rope and punch the trader',
        "route": '',
        "hazard": '',
        "scope": 'no_one_present',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the temple guard',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('temple-guard')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the temple guard and the child',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','temple',('temple-guard','market-child'),('rill',), both alive); _fight('temple-guard')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener over the monk',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','brother-monk'),(), brother-monk DEAD); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab the choir listener over the monk',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','brother-monk'),(), brother-monk ALIVE); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I stab the reed thug back',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm striking back at the reed thug",
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I strike back at the reed thug',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; combat=None and _fight('reed-thug', active=False)",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm attacking the wanderer",
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; combat=None and _fight('reed-thug', active=False)",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am stabbing the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; combat=None and _fight('reed-thug', active=False)",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; combat=None and _fight('reed-thug', active=False)",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('reed-thug','the-wanderer'),('rill',), both alive); _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I'm attacking the wanderer",
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('reed-thug','the-wanderer'),('rill',), both alive); _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I am stabbing the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('reed-thug','the-wanderer'),('rill',), both alive); _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the wanderer',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('reed-thug','the-wanderer'),('rill',), both alive); _fight('reed-thug')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack Rade with my razor whip',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack rade with my engraved longbow',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I strike Rade with the salt-crusted boarding hook',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I bring grandfather's notched harpoon down on Rade",
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I hurl the eel barrel at rade and follow with a wild haymaker',
        "route": '',
        "hazard": '',
        "scope": "other:no TrustedScope; _fight('rade')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I stab orso pell',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','orso-pell'),('rill',), both alive); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack the choir listener, then orso',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','orso-pell'),('rill',), both alive); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stab rill the healer',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','orso-pell'),('rill',), both alive); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I attack the choir listener immediately',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','orso-pell'),('rill',), both alive); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "I stab the choir listener now beside orso pell's body",
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('choir-listener','orso-pell'),('rill',), orso-pell DEAD); _fight('choir-listener')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'attack rade',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I stab the merchant',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'Punch a trader',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I punch the trader in the face and take the rope',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'kill the smuggler',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I burn the ledger',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I steal his purse',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I attack him',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'stab the guard and take the lamp',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I strangle the clerk with my rope',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'i attacked him',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'gm i had attacked and killed him. look at the transcript',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'the guard attacked me',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I attacked the fishmonger already, check the log',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'she killed my brother years ago',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'the thugs killed the bell-keeper before we arrived',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'he attacked me first, I swear',
        "route": 'risk',
        "hazard": '',
        "scope": "other:_SCOPE TrustedScope('session-1','the-eel-market',('rade','orso-pell'),('maren',), both alive)",
        "note": 'Regression case: risk; no positive hazard label.',
    },
    {
        "text": 'I search the crates',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I pick the lock',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I sneak past him',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I draw my knife',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'search the body',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I hide behind the barrel',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'follow him',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I pull the lever',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I push the door',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I count the coins',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I put on the ring',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I wait',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I rest',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'kneel',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'swim across',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'untie the mooring rope',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'empty his purse onto the table',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'trade places with the boy',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'whistle twice',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'cut my palm',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": '12',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('1','market',('orso-pell',),('rill',)) + active_focus InteractionCue('canonical_npc','orso-pell')",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take a break',
        "route": 'planner',
        "hazard": '',
        "scope": "other:_MARKET_SCOPE TrustedScope('1','market',('rade',))",
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'take the satchel',
        "route": 'planner',
        "hazard": '',
        "scope": "other:_MARKET_SCOPE TrustedScope('1','market',('rade',))",
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": 'how many turns would it take to reach the harbor?',
        "route": 'planner',
        "hazard": '',
        "scope": "other:_MARKET_SCOPE TrustedScope('1','market',('rade',))",
        "note": 'Regression case: planner; no positive hazard label.',
    },
    {
        "text": '@GM how many turns would it take to reach the harbor?',
        "route": 'out_of_character',
        "hazard": '',
        "scope": "other:_MARKET_SCOPE TrustedScope('1','market',('rade',))",
        "note": 'Regression case: out_of_character; no positive hazard label.',
    },
    {
        "text": 'buy nothing',
        "route": 'social',
        "hazard": '',
        "scope": "other:_MARKET_SCOPE TrustedScope('1','market',('rade',))",
        "note": 'Regression case: social; no positive hazard label.',
    },
    {
        "text": 'I tell the trader: "The buckle is scratched. I will offer 7 coins."',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Collect the buckle',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I pay 7 coins and collect the buckle',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": '@GM Why is collecting the agreed buckle blocked?',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'pay for the buckle',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Punch a trader',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Hurl a trader into the canal',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": "Pilfer the merchant's purse",
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Pulverize the town gate',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'Seal the door permanently',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I stab the barkeep',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I assault the librarian',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'kick orso',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I knee the guard',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'elbow the sailor',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'headbutt him',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'stomp the acolyte',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (requires_risk_confirmation default)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'take the ledger from orso pell',
        "route": '',
        "hazard": '',
        "scope": "other:TrustedScope('session-1','market',('orso-pell',),(),(('orso-pell','alive'),))",
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I persuade the clerk.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I deceive the clerk.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I rally the crowd.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I debate the facts.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I intimidate the guard.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I perform a song.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I ask for information.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I study their motive for insight.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I observe etiquette at court.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I promise to disclose the secret.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
    {
        "text": 'I bribe the clerk.',
        "route": '',
        "hazard": '',
        "scope": 'other:no scope (classify_social_input only)',
        "note": 'Regression case: context-dependent route; no positive hazard label.',
    },
]

# TOTAL: 316 unique (text, scope) cases, harvested from 355 labeled occurrences
# across 5 test modules; 39 repeat occurrences were merged into an existing
# case's note (same text, same scope, same asserted expectations).
# Per-source breakdown (unique cases):
#   test_interactions_risk_lexicon.py        244
#   test_social_interactions.py               31
#   test_probe_hazard_assessment.py           17
#   test_decisions.py                         13
#   tests/test_social_trade.py                11
#
# Coverage check: all 258 @pytest.mark.parametrize declaration strings and all 24
# inline classifier call-site declarations in test_interactions_risk_lexicon.py are
# present. The only two strings in that file deliberately excluded are the route
# names passed to turn_framing_for() at lines 1450-1451, which are not declarations.
